### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by CRT-HAO** [CWKevo/pyflarum#2]
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from pyflarum import FlarumUser
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pyflarum/__init__.py", line 1, in <module>
    from pyflarum.session import FlarumUser
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pyflarum/session.py", line 13, in <module>
    from .flarum.core.forum import Forum
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pyflarum/flarum/core/__init__.py", line 104, in <module>
    class BaseFlarumIndividualObject(BaseFlarumObject):
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pyflarum/flarum/core/__init__.py", line 161, in BaseFlarumIndividualObject
    def included(self) -> list[dict]:
TypeError: 'type' object is not subscriptable
```

**Comment by CWKevo** [comment]
As in #1, I think that this syntax was added in a later Python version (not sure which one, but maybe even 3.9.x). I'll look at options to fix this, I don't want to raise minimum version requirement just for types.

**Comment by CWKevo** [comment]
This uses the older `typing.List`, `typing.Dict`, etc... syntax, which is available in older Python versions. It should fix your issue
